name: fitness
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.1.0

  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0

  dots_indicator: ^3.0.0
  percent_indicator: ^4.0.1

  flutter_secure_storage: ^9.0.0

  chewie: ^1.7.4
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg